### ISSUE TITLE
Add Feature foxitrdr.pl

### ISSUE THREAD

**Issue by hyuunnn** [forensenellanebbia/RegRipper-plugins#1]
```
HKEY_CURRENT_USER\SOFTWARE\Foxit Software\Foxit Reader 10.0\CommentPanel\Filter\Record {number}\File
```
When deleting recent files from foxit reader, MRU is deleted, but this path is not deleted.

**Comment by forensenellanebbia** [comment]
I've added that additional path to the plugin. Thanks for the suggestion and happy new year!
